### ISSUE TITLE
Driver [google+] not supported.

### ISSUE THREAD

**Issue by Rub4ek** [SocialiteProviders/Google-Plus#1]
have this message
```
Driver [google+] not supported.
```
Other providers work fine.

**Comment by DraperStudio** [comment]
It should work with this, so only google instead of google+. Seems like a typo in the documentation.
```
return Socialite::with('google')->redirect();
```

**Comment by Rub4ek** [comment]
And this provider will override default socialite google provider, right? 
Then i have the same problem that i have in default provider
```
Client error response [url] https://www.googleapis.com/plus/v1/people/me [status code] 403 [reason phrase] Forbidden
```
This is a little off topic question, but I'll be grateful for the help. =)

**Comment by DraperStudio** [comment]
Have you enabled the scopes you are requesting in the Developer Console?

**Comment by Rub4ek** [comment]
Thanks, it works.
