### ISSUE TITLE
Google+ driver not found error

### ISSUE THREAD

**Issue by abishekrsrikaanth** [SocialiteProviders/Google-Plus#3]
According to the documentation @ http://socialiteproviders.github.io/providers/google+/#usage
The usage is 

`return Socialite::with('google+')->redirect();`

but using this it throws the error Google+ driver not found error

**Comment by DraperStudio** [comment]
This is a typo caused by how we generate the templates. Use this code instead

`return Socialite::with('google')->redirect();`

**Comment by abishekrsrikaanth** [comment]
Doing this, does it override the google driver already on socialite?

**Comment by DraperStudio** [comment]
If Providers share the same "namespace" and you have registered our Provider it should override the Socialite one if there is one.

**Comment by abishekrsrikaanth** [comment]
And using the new code suggested above, I get the Bad Request 400 error similar to that one posted few days back for LinkedIn

**Comment by DraperStudio** [comment]
Try the same solution as for the LinkedIn Provider.

**Comment by abishekrsrikaanth** [comment]
Did that, still facing the issue

This is what I have on composer json

```
"socialiteproviders/manager": "^1.0",
"socialiteproviders/google": "^1.1",
    "guzzlehttp/psr7": "dev-master"
```

**Comment by abishekrsrikaanth** [comment]
nvm, got it to work. Closing this issue. Thanks for the quick replies.
