### ISSUE TITLE
403 Error From Google

### ISSUE THREAD

**Issue by nicklee1990** [SocialiteProviders/Google-Plus#4]
I can successfully redirect the user to google but when they are returned to my site,I try to do

     Socialite::driver('google')->user()

which returns a 403 error - any idea why that may happen?

**Comment by DraperStudio** [comment]
Make sure you've setup your App correctly, this is often an issue which will cause 400 and 403 Errors.

**Comment by nicklee1990** [comment]
yeah just me being a clown
