### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by SohrabZ** [SocialiteProviders/Google-Plus#6]
After receiving callback from google this error will be shown :

FatalErrorException in AbstractProvider.php line 66:
Call to undefined method SocialiteProviders\Google\Provider::parseAccessToken()

I also receive this error when trying the instagram driver too.

**Comment by DraperStudio** [comment]
Do `dd(get_class_methods($this));` somewhere to see which methods are available.

**Comment by SohrabZ** [comment]
The problem mysteriously fixed after I deleted `vendor` folder and run `composer install` but thanks for your help.

**Comment by DraperStudio** [comment]
Alright, sometimes composer fails to override files so you probably were missing one from a previous `composer update`.
